/**
 * Why: runtime access to the same hex values as Tailwind theme (for tests, Storybook, or non-TW contexts).
 * What: frozen object copied from docs/STITCH_DESIGN_DNA.json `colors` — no guessing.
 */
export const STITCH_COLORS = {
  'inverse-primary': '#a9c7ff',
  'surface-variant': '#e0e3e6',
  'surface-tint': '#005db6',
  'on-secondary-fixed-variant': '#832700',
  'inverse-surface': '#2d3133',
  'on-surface': '#191c1e',
  'on-background': '#191c1e',
  'inverse-on-surface': '#eff1f4',
  'surface-container-lowest': '#ffffff',
  'on-tertiary': '#ffffff',
  'surface-container-high': '#e6e8eb',
  'surface-container': '#eceef1',
  outline: '#727783',
  'on-surface-variant': '#424752',
  primary: '#00478d',
  'primary-fixed': '#d6e3ff',
  'on-tertiary-fixed': '#071e27',
  'tertiary-container': '#4d626c',
  'secondary-fixed': '#ffdbcf',
  'surface-container-low': '#f2f4f7',
  'on-error-container': '#93000a',
  surface: '#f7f9fc',
  'secondary-fixed-dim': '#ffb59c',
  'error-container': '#ffdad6',
  error: '#ba1a1a',
  'tertiary-fixed-dim': '#b4cad6',
  'primary-fixed-dim': '#a9c7ff',
  'on-secondary-container': '#551600',
  'on-tertiary-container': '#c6dde9',
  'on-primary-fixed': '#001b3d',
  'outline-variant': '#c2c6d4',
  'on-tertiary-fixed-variant': '#354a53',
  'surface-bright': '#f7f9fc',
  'tertiary-fixed': '#cfe6f2',
  'surface-dim': '#d8dadd',
  'surface-container-highest': '#e0e3e6',
  'on-primary-fixed-variant': '#00468c',
  'primary-container': '#005eb8',
  tertiary: '#354a54',
  'on-primary-container': '#c8daff',
  background: '#f7f9fc',
  'on-error': '#ffffff',
  'on-primary': '#ffffff',
  'on-secondary': '#ffffff',
  secondary: '#ab3600',
  'secondary-container': '#fe5e1e',
  'on-secondary-fixed': '#390c00',
} as const;

export type StitchColorKey = keyof typeof STITCH_COLORS;
